/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BeveragesRouteImport } from './routes/beverages'
import { Route as CakesRouteImport } from './routes/cakes'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as PastriesRouteImport } from './routes/pastries'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeveragesRoute = BeveragesRouteImport.update({
  id: '/beverages',
  path: '/beverages',
  getParentRoute: () => rootRouteImport,
} as any)
const CakesRoute = CakesRouteImport.update({
  id: '/cakes',
  path: '/cakes',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const PastriesRoute = PastriesRouteImport.update({
  id: '/pastries',
  path: '/pastries',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beverages': typeof BeveragesRoute
  '/cakes': typeof CakesRoute
  '/menu': typeof MenuRoute
  '/our-story': typeof OurStoryRoute
  '/pastries': typeof PastriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beverages': typeof BeveragesRoute
  '/cakes': typeof CakesRoute
  '/menu': typeof MenuRoute
  '/our-story': typeof OurStoryRoute
  '/pastries': typeof PastriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beverages': typeof BeveragesRoute
  '/cakes': typeof CakesRoute
  '/menu': typeof MenuRoute
  '/our-story': typeof OurStoryRoute
  '/pastries': typeof PastriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/beverages' | '/cakes' | '/menu' | '/our-story' | '/pastries'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/beverages' | '/cakes' | '/menu' | '/our-story' | '/pastries'
  id:
    | '__root__'
    | '/'
    | '/beverages'
    | '/cakes'
    | '/menu'
    | '/our-story'
    | '/pastries'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeveragesRoute: typeof BeveragesRoute
  CakesRoute: typeof CakesRoute
  MenuRoute: typeof MenuRoute
  OurStoryRoute: typeof OurStoryRoute
  PastriesRoute: typeof PastriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beverages': {
      id: '/beverages'
      path: '/beverages'
      fullPath: '/beverages'
      preLoaderRoute: typeof BeveragesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cakes': {
      id: '/cakes'
      path: '/cakes'
      fullPath: '/cakes'
      preLoaderRoute: typeof CakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pastries': {
      id: '/pastries'
      path: '/pastries'
      fullPath: '/pastries'
      preLoaderRoute: typeof PastriesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeveragesRoute: BeveragesRoute,
  CakesRoute: CakesRoute,
  MenuRoute: MenuRoute,
  OurStoryRoute: OurStoryRoute,
  PastriesRoute: PastriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
